import { Head, Link } from '@inertiajs/react';
import { CheckCircle2, ShieldCheck } from 'lucide-react';
import AppLogo from '@/components/app-logo';
import ManageTwoFactor from '@/components/manage-two-factor';
import type { Props as ManageTwoFactorProps } from '@/components/manage-two-factor';
import { Button } from '@/components/ui/button';
import { dashboard } from '@/routes';

type Props = ManageTwoFactorProps & {
    flash: {
        status?: string;
    };
};

export default function AdminTwoFactorSetup({
    canManageTwoFactor,
    requiresConfirmation,
    twoFactorEnabled,
    flash,
}: Props) {
    const isConfirmed = twoFactorEnabled ?? false;

    return (
        <>
            <Head title="Secure your Control Room access" />
            <main className="min-h-screen bg-surface-sunken px-4 py-8 sm:px-6 lg:px-8">
                <div className="mx-auto w-full max-w-xl">
                    <Link
                        href="/"
                        className="rounded-md focus-visible:outline-none"
                    >
                        <AppLogo subtitle="Control Room security" />
                    </Link>

                    <section className="motion-panel-enter mt-10 rounded-2xl bg-surface p-6 ring-1 ring-border sm:p-8">
                        <div className="flex size-12 items-center justify-center rounded-xl bg-brand-soft text-brand">
                            {isConfirmed ? (
                                <CheckCircle2
                                    className="size-6"
                                    aria-hidden="true"
                                />
                            ) : (
                                <ShieldCheck
                                    className="size-6"
                                    aria-hidden="true"
                                />
                            )}
                        </div>

                        <p className="mt-6 text-xs font-semibold tracking-[0.16em] text-brand uppercase">
                            Control Room protection
                        </p>
                        <h1 className="mt-3 text-2xl font-semibold text-foreground">
                            {isConfirmed
                                ? 'Authenticator confirmed'
                                : 'Set up your authenticator app'}
                        </h1>
                        <p className="mt-3 text-sm leading-6 text-muted">
                            {isConfirmed
                                ? 'Your administrator account is protected. You can now enter the Control Room.'
                                : 'Scan the QR code with Google Authenticator, Microsoft Authenticator, Authy, or another TOTP app. Then enter the six-digit code generated by the app to unlock the Control Room.'}
                        </p>

                        {flash.status && (
                            <div className="bg-info-soft mt-5 rounded-xl px-4 py-3 text-sm font-medium text-info ring-1 ring-info/20">
                                {flash.status}
                            </div>
                        )}

                        {isConfirmed ? (
                            <Button asChild className="mt-6 w-full">
                                <Link href={dashboard()}>
                                    Open Control Room
                                </Link>
                            </Button>
                        ) : (
                            <div className="mt-8">
                                <ManageTwoFactor
                                    canManageTwoFactor={canManageTwoFactor}
                                    requiresConfirmation={requiresConfirmation}
                                    twoFactorEnabled={twoFactorEnabled}
                                />
                            </div>
                        )}
                    </section>
                </div>
            </main>
        </>
    );
}
